config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  get "/signup" , to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/user_posts", to: "users#posts"
  get "/posts/:id/softdelete", to: "posts#softdelete"
  resources :users ,except: [:new]
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to  :post

    belongs_to  :parent, class_name: 'Comment', optional: true
    has_many    :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

    validates :body, presence: true ,length: { maximum: 100 , message: " Comment Body must be less than 100 characters"}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :img
  has_many :comments ,dependent: :destroy
  has_paper_trail

  validates :title, presence: true ,length: { maximum: 20 ,minimum: 3, message:  " Title must be less than 20 characters "}
  validates :body, presence: true ,length: { maximum: 200 ,minimum: 3, message:  " Body must be less than 200 characters "}

  validates :img , presence: true ,file_size: { less_than_or_equal_to: 2.megabytes }, file_content_type: { allow: ['image/jpeg', 'image/png'] }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts , dependent: :destroy

  validates :username, presence: true, uniqueness: true , length: { in: 4..15 , message: 'Username length must be between 4 and 15' }
  validates :password, presence: true ,length: { in: 6..20 , message:  'Password length must be between 6 and 20'}
  validates :email, presence: true, uniqueness: true , format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "is not a valid email address" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_paper_trail_whodunnit
  helper_method :curret_user, :logged_in?

  def curret_user
    @curret_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!curret_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end


  def new
    if logged_in?
      @post = Post.find(params[:post_id])
      @comment = @post.comments.new(parent_id: params[:parent_id])
      @comment.commenter = session[:username]
    else
      redirect_to "/login"
    end
  end


  def create
    if logged_in?
      @post = Post.find(params[:post_id])
      @comment = @post.comments.new(comment_params)

      @comment.commenter = session[:username]
      respond_to do |format|
        if @comment.save
          format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        else
          @error_messages = @comment.errors.full_messages
          format.html { redirect_to "/new", notice: "Comment body could not be empty."}
        end
      end
    else
      redirect_to "/login"
    end
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    if(@comment.commenter == session[:username])
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to @comment.post, notice: 'Comment was successfully destroyed.'}
      end
    end

  end


  private
    def comment_params
      params.require(:comment).permit(:body, :post_id, :parent_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    if @post.soft
      redirect_to '/404.html'
    end
  end

  def new
    @error_messages = notice.presence
    @post = Post.new
  end

  def create
      @post = Post.new(post_params)
      @post.user_id = session[:user_id]
      @post.soft = false
      @error_messages = []

      if @post.save
            redirect_to @post
      else
        if !logged_in?
          @error_messages << "You must be logged in"
          redirect_to "/login"
        else
          @error_messages = @post.errors.full_messages
          redirect_to "/posts/new", notice: @error_messages
        end
      end

  end

  def edit
    @post = Post.find(params[:id])
    @error_messages = notice.presence
    if @post.user_id == session[:user_id]
      render :edit
    else
      @error_messages << "You must be logged in"
      redirect_to "/login"
    end
  end

  def update
    @post = Post.find(params[:id])
    @error_messages = []
    if @post.update(post_params)
      redirect_to @post
    else
      @error_messages = @post.errors.full_messages
      redirect_to "/posts/edit", notice: @error_messages
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == session[:user_id]
      @post.destroy
      redirect_to posts_path, status: :see_other
    else
      redirect_to "/login"
    end
  end

  def softdelete
    @post = Post.find(params[:id])
    if @post.user_id == session[:user_id]
      soft = !@post.soft
      @post.update(:soft => soft)
      redirect_to posts_path()
    else
      redirect_to "/login"
    end
  end


  private
  def post_params
    params.require(:post).permit(:title, :img , :body, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    respond_to do |format|
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        session[:username] = @user.username
        format.html { redirect_to posts_path(), notice: 'Logged in successfully' }
        format.json { render :show , status: :created, location: @user}
      else
        format.html { redirect_to login_path(), notice: "Invalid username or password" }
      end
    end
  end

  def destroy
    session[:user_id] = nil
    session[:email] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @error_messages = notice.presence
  end

  def posts
    if logged_in?
      @user = User.find(session[:user_id])
      @posts = @user.posts.all
    else
      redirect_to "/login" , notice: "You must be logged in to view your posts"
    end
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        flash[:notice] = "User created successfully"
        format.html { redirect_to login_path(), notice1: "User created successfully .PLease Login to continue" }
        format.json { render :show , status: :created, location: @user}
      else
        @error_messages = @user.errors.full_messages
        format.html { redirect_to signup_path(), notice: @error_messages }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% unless comment.parent_id || !comment.persisted? %>
  <p>
    <strong><%= comment.commenter %></strong>
    <%= comment.body %>
    <% if logged_in? %>
      <%= link_to 'reply', new_post_comment_path(@post, parent_id: comment.id), remote: true %>
        <%if comment.commenter == session[:username]%>
          <%= link_to "delete" , post_comment_path(@post ,comment_id: comment.id), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                          } %>
        <%end%>
    <%end%>
  </p>
   <%= render partial: "comments/reply_comments" ,locals: {post: @post , comment: comment} %>

<% end %>

app/views/comments/_reply_comments.html.erb
  <% if comment && comment.replies.any? %>
    <% comment.replies.each do |reply| %>
      <ul>
        <li><strong><%=reply.commenter %></strong>: <%=reply.body%></li>
        <% if logged_in? %>
          <%= link_to 'reply', new_post_comment_path(@post, parent_id: reply.id), remote: true %>
            <%if reply.commenter == session[:username]%>
              <%= link_to "delete" , post_comment_path(@post ,comment_id: reply.id), data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure?"
                              } %>
            <%end%>
        <%end%>
        <%= render partial: "comments/reply_comments" ,locals: {post: @post , comment: reply} %>
      </ul>
    <% end %>
  <% end %>

app/views/comments/new.html.erb
<div>
  <h4> REPLY TO COMMENT </h4>
  <%= form_with(model: [@post, @comment]) do |f| %>
    <%= f.hidden_field :parent_id %>
    <div class="form-group">
      <%= f.label 'Reply' %>
      <%= f.text_area :body %>
    </div>
    <%= f.submit 'Submit' %>
    <%= link_to 'Cancel', post_path(@post) %>
    <p style = "color: green"><%= notice %></p> 
  <% end %>
</div>

app/views/comments/new.js.erb
document.querySelector("#reply-form-<%= @comment.parent_id %>").innerHTML = ("<%= j render partial: 'new', comment: @comment %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <br/>

  <%= form.label :image %>
  <%= form.file_field :img %>
  <br/>
  <%= form.label :body %>
  <%= form.text_field :body %>
  <br/>
  <% if @error_messages %>
    <div id="error_explanation">
      <h2><%= pluralize(@error_messages.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @error_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.submit %>
<% end %>

app/views/posts/index.html.erb
<p style = "color: green"><%= notice %></p>
<h1>INSTAGRAM</h1>


<% if logged_in? %>
 <strong>Current User:
  <%= session[:username] %>
  <%= link_to "Logout", logout_path %>
  <%= link_to "My Posts" ,"/user_posts"%>
<%else%>
  <%= link_to "Login" ,login_path() %>
  <br/>
  <%= link_to "New User? Create Account" ,signup_path() %>
<%end%>

<br/>

<% if logged_in? %>

  <%= link_to "New Post", new_post_path %>
<%end%>



<ul>
  <% @posts.each do |post| %>
    <% if !post.soft %>
      <li>
      <a href = "/posts/<%= post.id %>">

        <%= post.title %>
        <%= image_tag (post.img), style: "height:250px; ,width: 250px;"%>

      </li>
    <%end%>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <br/>

  <%= form.label :image %>
  <%= form.file_field :img %>
  <br/>
  <%= form.label :Body %>
  <%= form.text_field :body %>
  <br/>
  <% if @error_messages %>
    <div id="error_explanation">
      <h2><%= pluralize(@error_messages.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @error_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><a href = "http://localhost:3000/posts"> Home</a></h1>

<h1><%= @post.title %></h1>
<%= image_tag (@post.img), style: "height:250px; ,width: 250px;"%>
<br/>
<strong> Body : </strong> <%= @post.body %>


<% if session[:user_id] == @post.user_id%>
  <ul>
    <li><%= link_to "Edit", edit_post_path(@post) %></li>
    <li><%= link_to "Archive", "/posts/#{@post.id}/softdelete"%> </li>
    <li><%= link_to "Delete" , post_path(@post), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                          } %></li>
  </ul>
<%end%>



<div >
    <%= form_with(model: [@post, @post.comments.build]) do |f| %>
      <div>
        <%= f.label 'New comment' %>
        <%= f.text_area :body %>
      </div>
      <%= f.submit 'Submit' %>
    <%end%>
</div>
<p style = "color: green"><%= notice %></p>
<br/>
<strong>Comments  </strong>

<%= render @post.comments %>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |f| %>

<div>
  <%= f.label :username %><br/>
  <%= f.text_field :username %>
</div>

<div>
  <%= f.label :email %><br/>
  <%= f.email_field :email%>
</div>

<div >
  <%= f.label :password %><br/>
  <%= f.password_field :password %>
</div>
 <% if @error_messages %>
    <div id="error_explanation">
      <h2><%= pluralize(@error_messages.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @error_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div >
  <%= f.submit %>
</div>

<% end %>

app/views/users/posts.html.erb
<h1><a href = "http://localhost:3000/posts"> Home</a></h1>
<h1>My Posts</h1>


<% if @posts.present?%>
    <ul>
    <% @posts.each do |post| %>


         <li>
                <%= post.title %>
                <%= image_tag (post.img), style: "height:100px; ,width: 100px;"%>

        </li>
        <% if !post.soft %>
            <%= link_to "Archive", "/posts/#{post.id}/softdelete"%>
        <%else%>
            <%= link_to "Unarchive", "/posts/#{post.id}/softdelete"%>
        <%end%>

    <% end %>
    </ul>
<% else %>
    <h3> You have no posts</h3>
    <%= link_to "Create your first post" , new_post_path() %>
<%end%>